### ISSUE TITLE
RoR group project : set up Kanban board

### ISSUE THREAD

**Issue by ANTOINE1128** [ANTOINE1128/Recipe-App-project#11]
# We are two developers working on this project 
https://github.com/users/ANTOINE1128/projects/11/views/1

**Comment by DammyShittu** [comment]
Hi @ANTOINE1128 and @wolterbwambale,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### I cannot review your project. It could be that your link is broken or set to private.

![image](https://github.com/ANTOINE1128/Recipe-App-project/assets/54848363/7efcde95-e340-400b-aaf3-f6b8dcca21c3)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @ANTOINE1128 and @wolterbwambale,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are well-assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Only one task has a description. Kindly add a description for all your tasks. Here is an example of task that has no description.

  ![image](https://github.com/ANTOINE1128/Recipe-App-project/assets/36542986/ca3d70b0-fc70-4b0e-93d9-65659458e233)

- [ ] These two tasks are duplicates of each other. Kindly remove one.

  ![image](https://github.com/ANTOINE1128/Recipe-App-project/assets/36542986/13547061-86b0-4caa-b154-4076f1dcfce9)

- [ ] Kindly add an issue for this task.

  ![image](https://github.com/ANTOINE1128/Recipe-App-project/assets/36542986/47123736-d6ed-44c3-9f03-a745c2b2484e)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
Hi @ANTOINE1128 and @wolterbwambale,

Good job so far!

## Highlights!
- Descriptive issues ✔️ 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] Kindly ensure all tasks have descriptions as requested by the previous reviewer. This issue has no description, kindly add it.

  ![image](https://github.com/ANTOINE1128/Recipe-App-project/assets/81468675/91bf8c3b-49a7-45bf-8515-930e130bb5db)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>
## Highlights
- Required changes fixed ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
